style:
  # This rule simply drives me mad.
  MagicNumber:
    active: false
  ForbiddenComment:
    allowedPatterns: "[ALPHA]"
naming:
  # Never liked this rule. I do what I want!
  TopLevelPropertyNaming:
    active: false
  FunctionNaming:
    # I'll name functions however I feel
    active: false
complexity:
  CyclomaticComplexMethod:
    ignoreSingleWhenExpression: true